name: Update version.json

on:
  push:
    branches:
      - main
    paths-ignore:
      - "version.json"

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get commit info
        id: commit
        run: |
          echo "date=$(git log -1 --format=%cd --date=iso-strict)" >> $GITHUB_OUTPUT
          echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Update version.json
        run: |
          echo "{\"date\": \"${{ steps.commit.outputs.date }}\", \"hash\": \"${{ steps.commit.outputs.hash }}\"}" > version.json

      - name: Commit and push version.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add version.json
          git commit -m "Update version.json [skip ci]" || echo "No changes to commit"
          git push
