name: Update version.json and sitemap.xml

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths-ignore:
      - "version.json"
      - "sitemap.xml"

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Get commit info
        id: commit
        run: |
          echo "date=$(git log -1 --format=%cd --date=iso-strict)" >> $GITHUB_OUTPUT
          echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Update version.json
        run: |
          echo "{\"date\": \"${{ steps.commit.outputs.date }}\", \"hash\": \"${{ steps.commit.outputs.hash }}\"}" > version.json

      - name: Update sitemap.xml
        run: |
          DATE="${{ steps.commit.outputs.date }}"
          SITEMAP="sitemap.xml"

cat <<EOF > "$SITEMAP"
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="https://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="https://www.w3.org/1999/xhtml">
  <url>
    <loc>https://17number.github.io/enr-relics-merger/</loc>
    <lastmod>$DATE</lastmod>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
    <xhtml:link rel="alternate" hreflang="ja" href="https://17number.github.io/enr-relics-merger/" />
    <xhtml:link rel="alternate" hreflang="en" href="https://17number.github.io/enr-relics-merger/en/" />
  </url>

  <url>
    <loc>https://17number.github.io/enr-relics-merger/privacy.html</loc>
    <lastmod>$DATE</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
    <xhtml:link rel="alternate" hreflang="ja" href="https://17number.github.io/enr-relics-merger/privacy.html" />
    <xhtml:link rel="alternate" hreflang="en" href="https://17number.github.io/enr-relics-merger/en/privacy.html" />
  </url>

  <url>
    <loc>https://17number.github.io/enr-relics-merger/en/</loc>
    <lastmod>$DATE</lastmod>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
    <xhtml:link rel="alternate" hreflang="ja" href="https://17number.github.io/enr-relics-merger/" />
    <xhtml:link rel="alternate" hreflang="en" href="https://17number.github.io/enr-relics-merger/en/" />
  </url>

  <url>
    <loc>https://17number.github.io/enr-relics-merger/en/privacy.html</loc>
    <lastmod>$DATE</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
    <xhtml:link rel="alternate" hreflang="ja" href="https://17number.github.io/enr-relics-merger/privacy.html" />
    <xhtml:link rel="alternate" hreflang="en" href="https://17number.github.io/enr-relics-merger/en/privacy.html" />
  </url>

</urlset>
EOF

      - name: Commit and push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add version.json sitemap.xml
          git commit -m "Update version.json and sitemap.xml [skip ci]" || echo "No changes to commit"
          git push
